FROM python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /app


# Install Python dependencies
COPY src/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt


# Copy the project files to the container
COPY . /app

CMD ["streamlit", "run", "src/asi/main.py"]