FROM python:3.10-slim-buster

WORKDIR /app

COPY src/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

# Run the Python script
CMD ["python", "src/asi/utils/make_report.py"]