wandb_version: 1

max_depth:
  desc: null
  value: null
n_estimators:
  desc: null
  value: 300
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686771349.524458
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.10.6
      5: 0.15.3
      8:
      - 5
